"""empty message

Revision ID: a03242ab93b8
Revises:
Create Date: 2023-09-11 20:04:57.412456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03242ab93b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('org_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('symbol', sa.String(length=255), nullable=False),
                    sa.Column('current_price', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('symbol')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=40), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('wallet', sa.Float(
                        precision=100), nullable=True),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('user_portfolios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('market_value', sa.Float(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('portfolio_stocks',
                    sa.Column('user_portfolios', sa.Integer(), nullable=False),
                    sa.Column('stocks', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['stocks'], ['stocks.id'], ),
                    sa.ForeignKeyConstraint(['user_portfolios'], [
                                            'user_portfolios.id'], ),
                    sa.PrimaryKeyConstraint('user_portfolios', 'stocks')
                    )
    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=255), nullable=False),
                    sa.Column('total', sa.Integer(), nullable=True),
                    sa.Column('portfolio_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['portfolio_id'], ['user_portfolios.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('stock_transactions',
                    sa.Column('transactions', sa.Integer(), nullable=False),
                    sa.Column('stocks', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['stocks'], ['stocks.id'], ),
                    sa.ForeignKeyConstraint(
                        ['transactions'], ['transactions.id'], ),
                    sa.PrimaryKeyConstraint('transactions', 'stocks')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transactions')
    op.drop_table('transactions')
    op.drop_table('portfolio_stocks')
    op.drop_table('user_portfolios')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
