"""empty message

<<<<<<< HEAD:backend/migrations/versions/41f0ac30f482_.py
Revision ID: f9fe25afb844
Revises: 
Create Date: 2023-08-25 16:58:07.727909
=======
Revision ID: ebbde634ce21
Revises: 
Create Date: 2023-08-27 16:08:48.718918
>>>>>>> f9041c6c49f4249ad9688014190b50c7c4cae79d:backend/migrations/versions/ebbde634ce21_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:backend/migrations/versions/41f0ac30f482_.py
revision = 'f9fe25afb844'
=======
revision = 'ebbde634ce21'
>>>>>>> f9041c6c49f4249ad9688014190b50c7c4cae79d:backend/migrations/versions/ebbde634ce21_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('currentPrice', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('wallet', sa.Float(precision=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Float(precision=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_stock', sa.Integer(), nullable=True),
    sa.Column('stock_num', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_stocks',
    sa.Column('user_portfolios', sa.Integer(), nullable=False),
    sa.Column('stocks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stocks'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_portfolios'], ['user_portfolios.id'], ),
    sa.PrimaryKeyConstraint('user_portfolios', 'stocks')
    )
    op.create_table('stock_transactions',
    sa.Column('transactions', sa.Integer(), nullable=False),
    sa.Column('stocks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stocks'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['transactions'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('transactions', 'stocks')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transactions')
    op.drop_table('portfolio_stocks')
    op.drop_table('user_portfolios')
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
